### ISSUE TITLE
How to add blog section to the them?

### ISSUE THREAD

**Issue by rajasekhar-gundala** [diego-alfadev/alfadev-astro-starter#2]
Hi Thank you very much for the theme.

Is there a way to add blog collection to it? I tried to create posts folder in Content collection. But no look.

do the needful.

**Comment by diego-alfadev** [comment]
Hello there!

Thanks for giving my template a change, im glad to hear u liked it.


To awnser your question, i don't think the issue here is related to the theme.

Have you ever heard of the [Content Collections API](https://docs.astro.build/en/guides/content-collections/) in Astro?. This is the traditional way of adding dynamic pages based on content, as the docs say.

There you can find more information about how to build dynamic pages based on a defined collection (in this case, the blog), go directly to the ["Generating Routes from Content"](https://docs.astro.build/en/guides/content-collections/#generating-routes-from-content) section, to know more about this amazing Astro feature.

**However, i encourage you to implement it following the new [Content Layer API](https://docs.astro.build/en/guides/upgrade-to/v5/#updating-existing-collections)** introduced in the 5.0 version, which will be released as stable soon.

Hope this helps, please close the issue if that helped.
Best Regards.
